import React, { useState } from "react";
import Head from "next/head";
import { Project } from "../components/Project";
import { Footer } from "../components/Footer";
import { Navbar } from "../components/Navbar";

import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";

/** ----- icons ----- */
import { AiFillGithub } from "react-icons/ai";
import Designs from "../components/Designs";
import Tools from "../components/Tools";
import Hero from "../components/Hero";
import Skills from "../components/Skills";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Pratik Chavan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
        <section className="mx-auto my-10">
          <Hero />
        </section>

        {/** ------- lang section ------- */}

        <section className="my-[180px] text-center">
          <Skills />
        </section>

        {/** ------- tools section ------- */}

        <section className="my-[180px] text-center">
          <Tools />
        </section>

        {/** ------- work section ------- */}

        <section className="py-10 text-center">
          <Project />
        </section>

        <section className="my-20">
          <div className="group flex justify-evenly ">
            <div className="flex justify-center gap-2 px-4 cursor-pointer justify-items-center group-hover:bg-white group-hover:text-gray-900 group-hover:border-white rounded-full p-2 border-2 border-teal-600 dark:text-white">
              <AiFillGithub className="text-3xl" />
              <p className="text-xl font-medium ">Learn more about my work</p>
            </div>
          </div>
        </section>
        <section className="my-20">
          <Designs />
        </section>

        <Footer />
      </main>
    </div>
  );
}
